'use client';
// PrintLetterhead — the top and bottom of a report saved as PDF: the shop's letterhead, report name and
// details, and a sign-off. Only shown when printing. Use savePdf() to name the file after the report.

import React from 'react';
import { MERCHANT } from '@/lib/merchant';

export const LETTERHEAD_CSS = `
.pl-doc{display:none}
@media print{
  @page{size:A4 portrait;margin:14mm 12mm 16mm;@bottom-left{content:"${MERCHANT.name} · confidential";font-family:var(--font-sans);font-size:8pt;color:#64748b}@bottom-right{content:"Page " counter(page) " of " counter(pages);font-family:var(--font-sans);font-size:8pt;color:#64748b}}
  html,body{background:#fff!important}
  *{-webkit-print-color-adjust:exact;print-color-adjust:exact}
  .pl-doc{display:block}
  .gc-pagehead{display:none!important}
  .pl-head{display:flex;justify-content:space-between;align-items:flex-start;gap:24px;padding-bottom:12px;border-bottom:2px solid var(--primary);margin-bottom:12px}
  .pl-brand{display:flex;gap:12px;align-items:flex-start}
  .pl-brand b{display:block;font-size:15pt;font-weight:var(--weight-semibold);color:var(--text-heading)}
  .pl-brand span{display:block;font-size:8pt;line-height:1.5;color:var(--text-body)}
  .pl-meta{text-align:right;max-width:55%}
  .pl-kind{display:block;font-size:8pt;letter-spacing:.08em;text-transform:uppercase;color:var(--primary);font-weight:var(--weight-semibold)}
  .pl-meta h2{margin:2px 0 6px;font-size:17pt;line-height:1.2;font-weight:var(--weight-semibold);color:var(--text-heading)}
  .pl-meta dl{margin:0;display:grid;grid-template-columns:auto auto;justify-content:end;gap:1px 10px;font-size:8pt}
  .pl-meta dt{color:var(--text-muted)}
  .pl-meta dd{margin:0;color:var(--text-heading);font-weight:var(--weight-medium);text-align:right}
  .pl-sign{display:grid;grid-template-columns:repeat(3,1fr);gap:28px;margin-top:34px;break-inside:avoid}
  .pl-sign div{border-top:1px solid var(--text-body);padding-top:4px;font-size:8pt;color:var(--text-muted)}
  .pl-end{margin-top:10px;font-size:7.5pt;color:var(--text-muted)}
  .gc-card{box-shadow:none!important;border:1px solid var(--border-subtle)!important;break-inside:avoid}
  .gc-card:has(table){break-inside:auto}
}
`;

export function PrintLetterhead({ kind, title, meta = [] }) {
  return (
    <div className="pl-doc" aria-hidden="true">
      <header className="pl-head">
        <div className="pl-brand">
          <svg width="44" height="44" viewBox="0 0 52 52"><rect width="52" height="52" rx="12" fill="var(--primary)" /><path d="M35 19a10 10 0 1 0 1 13v-6h-9" fill="none" stroke="#fff" strokeWidth="4" strokeLinecap="round" strokeLinejoin="round" /></svg>
          <div><b>{MERCHANT.name}</b><span>{MERCHANT.address}</span><span>{MERCHANT.phone} · {MERCHANT.email}</span><span>{MERCHANT.web} · BIN {MERCHANT.bin}</span></div>
        </div>
        <div className="pl-meta">
          <span className="pl-kind">{kind}</span>
          <h2>{title}</h2>
          <dl>{meta.map(([k, v]) => <React.Fragment key={k}><dt>{k}</dt><dd>{v}</dd></React.Fragment>)}</dl>
        </div>
      </header>
    </div>
  );
}

export function PrintSignOff({ when }) {
  return (
    <div className="pl-doc" aria-hidden="true">
      <div className="pl-sign"><div>Prepared by</div><div>Checked by</div><div>Approved by</div></div>
      <p className="pl-end">Generated by GridCommerce on {when}. Figures as recorded in the shop’s books at that time.</p>
    </div>
  );
}

/** Open the browser's print dialog with the page title set, so "Save as PDF" names the file well. */
export function savePdf(fileTitle) {
  const before = document.title;
  document.title = `${MERCHANT.name} - ${fileTitle}`;
  window.print();
  setTimeout(() => { document.title = before; }, 500);
}
